Fix undefined reference to "_Errno" and add prx sample undefined reference to "_Errno" when linking the library to another project which is calling the functions of the library